### ISSUE TITLE
The PSNR values for "tornado" and "five_jets" are lower compared to the data in the article.

### ISSUE THREAD

**Issue by buaa-liu** [TouKaienn/STSR-INR#1]
![five_jet](https://github.com/user-attachments/assets/715d8eef-e116-4dd5-a778-b4ac6052f3e3)

Why is the PSNR value relatively low when I use the five_jet dataset? Where might the problem lie?

**Comment by TouKaienn** [comment]
Hi,

Thanks for pointing this out! I noticed the value range of the five_jet dataset we shared is [0, 1]. It should be [-1, 1], which is the value range of our model output. I have updated the five_jet dataset in the shared Google Drive link.

**Comment by buaa-liu** [comment]
Thank you for your response. Based on your re-uploaded datasets and updated suggestions, I have noticed that the numerical range of the vortex dataset is not between -1 and 1. Additionally, following your training method, the PSNR (Peak Signal-to-Noise Ratio) for the five_jets dataset is still lower than expected. Does this indicate a problem with the configuration parameters on my end?
![five_jets](https://github.com/user-attachments/assets/1a62ed63-2da1-45fa-9ba2-4f6bfa71ac82)
![vortex](https://github.com/user-attachments/assets/42fda9a8-726a-49ea-bab2-7356db0d728f)
![config_vortex](https://github.com/user-attachments/assets/64a8cf53-b7a5-4cb8-9816-fa030b3bb731)

**Comment by TouKaienn** [comment]
Yes, for this experiment, we set the spatial upscaling factor to 2x instead of 4x. Please refer to our config file located in configs/jointTrain.yml for more information.

**Comment by TouKaienn** [comment]
Closed as inactive, feel free to reopen this issue if necessary.
